FrontEndBundle\Entity\Clima:
    properties:
        nombre:
            - NotBlank: {message: "El nombre no puede ser vacio"}
            - Length:
                min: 4
                minMessage: "El nombre tiene que tener mas de 4 caracteres"